import test from 'node:test';
import assert from 'node:assert/strict';
import { validateMapsUrl, parseRating, workerCount, mapsIdentity, parseLocalizedCount, extractCountFromReviewLabel } from '../src/services/scraperUtils.js';
import { calendarDate } from '../src/utils/date.js';
test('missing ratings remain null',()=>{assert.equal(parseRating(''),null);assert.equal(parseRating('4,7'),4.7);assert.equal(parseRating('6'),null);});
test('Vietnam date around midnight',()=>{assert.equal(calendarDate('2026-10-06T19:00:00Z'),'2026-10-07');assert.equal(calendarDate('2026-10-06T16:59:00Z'),'2026-10-06');});
test('official Maps URLs only',()=>{for(const url of ['https://google.com.example.org/maps','http://www.google.com/maps','https://user:pass@www.google.com/maps','https://www.google.com/search','https://goo.gl/other']) assert.throws(()=>validateMapsUrl(url)); assert.ok(validateMapsUrl('https://maps.app.goo.gl/abc'));});
test('worker configuration fallback and cap',()=>{assert.equal(workerCount('abc',20),3);assert.equal(workerCount('100',20),5);assert.equal(workerCount('0',20),3);assert.equal(workerCount('3',1),1);});
test('same Maps CID with different URL forms',()=>{assert.equal(mapsIdentity('https://www.google.com/maps?cid=255'),mapsIdentity('https://www.google.com/maps/place/A/data=!1s0x12:0xff'));});
test('exact localized counts; reject rounded and ratings',()=>{for(const value of ['1,234','1.234','1 234','(1.234)'])assert.equal(parseLocalizedCount(value),1234);assert.equal(parseLocalizedCount('4.9'),null);assert.equal(parseLocalizedCount('1.2K'),null);assert.equal(extractCountFromReviewLabel('1.234 đánh giá'),1234);assert.equal(extractCountFromReviewLabel('1.2K reviews'),null);assert.equal(extractCountFromReviewLabel('reviews: 123'),123);});
