-- Run the whole file in Supabase SQL Editor as postgres.
-- Additive and rerunnable; only review_tracker_* objects are affected.
begin;
create table if not exists public.review_tracker_places (
  id bigint generated by default as identity primary key,
  place_id text not null unique,
  name text not null check (char_length(name) between 1 and 200),
  custom_name text, address text not null default '',
  rating numeric check (rating between 0 and 5),
  user_rating_count bigint not null default 0 check (user_rating_count >= 0),
  google_maps_uri text not null, tracked integer not null default 1,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  last_sync_at timestamptz, last_error text
);
create table if not exists public.review_tracker_snapshots (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.review_tracker_places(id) on delete cascade,
  date date not null, captured_at timestamptz not null,
  user_rating_count bigint not null check (user_rating_count >= 0),
  rating numeric check (rating between 0 and 5), unique (place_id, date)
);
create table if not exists public.review_tracker_kv (
  key text primary key, value jsonb not null, expires_at timestamptz not null
);
create table if not exists public.review_tracker_locks (
  name text primary key, token text not null, expires_at timestamptz not null
);
alter table public.review_tracker_places add column if not exists google_account text;
alter table public.review_tracker_places add column if not exists google_location text;
alter table public.review_tracker_places add column if not exists data_source text not null default 'scraper';
create unique index if not exists review_tracker_google_location_unique on public.review_tracker_places(google_location) where google_location is not null;
create table if not exists public.review_tracker_connections (
 id text primary key, payload text not null, revision uuid not null default gen_random_uuid(), updated_at timestamptz not null default now()
);
alter table public.review_tracker_connections enable row level security;
revoke all on public.review_tracker_connections from public,anon,authenticated;
grant select,insert,update,delete on public.review_tracker_connections to service_role;

alter table public.review_tracker_places enable row level security;
alter table public.review_tracker_snapshots enable row level security;
alter table public.review_tracker_kv enable row level security;
alter table public.review_tracker_locks enable row level security;
revoke all on public.review_tracker_places, public.review_tracker_snapshots,
  public.review_tracker_kv, public.review_tracker_locks from public, anon, authenticated;
grant select, insert, update, delete on public.review_tracker_places, public.review_tracker_snapshots,
  public.review_tracker_kv, public.review_tracker_locks to service_role;
revoke all on sequence public.review_tracker_places_id_seq, public.review_tracker_snapshots_id_seq from public, anon, authenticated;
grant usage, select on sequence public.review_tracker_places_id_seq, public.review_tracker_snapshots_id_seq to service_role;

create or replace function public.review_tracker_state() returns jsonb
language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object(
    'places', coalesce((select jsonb_object_agg(id::text,to_jsonb(p)) from public.review_tracker_places p), '{}'::jsonb),
    'snapshots', coalesce((select jsonb_object_agg(id::text,to_jsonb(s)) from public.review_tracker_snapshots s), '{}'::jsonb)
  );
$$;
create or replace function public.review_tracker_mutate(p jsonb) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare
  row_data public.review_tracker_places%rowtype;
  fresh jsonb := p->'fresh';
  place_key text := p->>'identity';
  row_id bigint := (p->>'id')::bigint;
  captured timestamptz := (p->>'now')::timestamptz;
  snapshot_date date := (p->>'date')::date;
  custom text := nullif(trim(p->>'custom'),'');
begin
  if p->>'op' = 'save' then
    if row_id is not null then
      update public.review_tracker_places as t set
        place_id=coalesce(place_key,t.place_id),google_account=coalesce(fresh->>'googleAccount',t.google_account),google_location=coalesce(fresh->>'googleLocation',t.google_location),data_source=coalesce(fresh->>'dataSource',t.data_source),
        custom_name=coalesce(custom,t.custom_name),name=coalesce(custom,t.custom_name,fresh->>'name'),
        address=coalesce(fresh->>'address',''), rating=(fresh->>'rating')::numeric,
        user_rating_count=(fresh->>'reviewCount')::bigint, google_maps_uri=fresh->>'url',
        updated_at=captured, last_sync_at=captured, last_error=null
      where t.id=row_id returning * into row_data;
      if not found then raise exception using errcode='P0002', message='Place not found'; end if;
    else
      insert into public.review_tracker_places as t
        (place_id,name,custom_name,address,rating,user_rating_count,google_maps_uri,updated_at,last_sync_at,google_account,google_location,data_source)
      values (place_key,coalesce(custom,fresh->>'name'),custom,coalesce(fresh->>'address',''),
        (fresh->>'rating')::numeric,(fresh->>'reviewCount')::bigint,fresh->>'url',captured,captured,fresh->>'googleAccount',fresh->>'googleLocation',coalesce(fresh->>'dataSource','scraper'))
      on conflict (place_id) do update set
        google_account=excluded.google_account,google_location=excluded.google_location,data_source=excluded.data_source,
        custom_name=coalesce(excluded.custom_name,t.custom_name),
        name=coalesce(excluded.custom_name,t.custom_name,excluded.name),
        address=excluded.address,rating=excluded.rating,user_rating_count=excluded.user_rating_count,
        google_maps_uri=excluded.google_maps_uri,updated_at=captured,last_sync_at=captured,last_error=null
      returning * into row_data;
    end if;
    insert into public.review_tracker_snapshots as s
      (place_id,date,captured_at,user_rating_count,rating)
    values (row_data.id,snapshot_date,captured,row_data.user_rating_count,row_data.rating)
    on conflict (place_id,date) do update set
      captured_at=excluded.captured_at,user_rating_count=excluded.user_rating_count,rating=excluded.rating;
    return to_jsonb(row_data);
  elsif p->>'op' = 'rename' then
    update public.review_tracker_places set name=p->>'name',custom_name=p->>'name',updated_at=captured
      where id=row_id returning * into row_data;
    if not found then raise exception using errcode='P0002', message='Place not found'; end if;
    return to_jsonb(row_data);
  elsif p->>'op' = 'delete' then
    delete from public.review_tracker_places where id=row_id;
    if not found then raise exception using errcode='P0002', message='Place not found'; end if;
  elsif p->>'op' = 'error' then
    update public.review_tracker_places set last_error=p->>'error' where id=row_id;
  else raise exception 'Unknown operation';
  end if;
  return '{"ok":true}'::jsonb;
end;
$$;
create or replace function public.review_tracker_lock(p_name text,p_token text,p_seconds integer) returns boolean
language plpgsql security invoker set search_path = '' as $$
declare count_rows integer;
begin
  insert into public.review_tracker_locks as t(name,token,expires_at)
  values (p_name,p_token,now()+make_interval(secs=>greatest(1,least(p_seconds,300))))
  on conflict (name) do update set token=excluded.token,expires_at=excluded.expires_at
    where t.expires_at<=now();
  get diagnostics count_rows = row_count;
  return count_rows=1;
end;
$$;
create or replace function public.review_tracker_unlock(p_name text,p_token text) returns void
language sql security invoker set search_path = '' as $$
  delete from public.review_tracker_locks where name=p_name and token=p_token;
$$;
create or replace function public.review_tracker_kv_get(p_key text) returns jsonb
language sql stable security invoker set search_path = '' as $$
  select value from public.review_tracker_kv where key=p_key and expires_at>now();
$$;
create or replace function public.review_tracker_kv_set(p_key text,p_value jsonb,p_seconds integer) returns void
language plpgsql security invoker set search_path = '' as $$
begin
  delete from public.review_tracker_kv where expires_at<=now();
  insert into public.review_tracker_kv as t(key,value,expires_at)
  values (p_key,p_value,now()+make_interval(secs=>greatest(1,least(p_seconds,604800))))
  on conflict (key) do update set value=excluded.value,expires_at=excluded.expires_at;
end;
$$;
create or replace function public.review_tracker_kv_delete(p_key text) returns void
language sql security invoker set search_path = '' as $$
  delete from public.review_tracker_kv where key=p_key;
$$;

create or replace function public.review_tracker_kv_take(p_key text) returns jsonb
language plpgsql security invoker set search_path='' as $$
declare result jsonb;
begin
 delete from public.review_tracker_kv where key=p_key and expires_at>now() returning value into result;
 return result;
end;
$$;
create or replace function public.review_tracker_connection_get() returns jsonb
language sql stable security invoker set search_path='' as $$
 select jsonb_build_object('payload',payload,'revision',revision) from public.review_tracker_connections where id='google';
$$;
create or replace function public.review_tracker_connection_set(p_payload text,p_expected_revision uuid default null) returns jsonb
language plpgsql security invoker set search_path='' as $$
declare row_data public.review_tracker_connections%rowtype;
begin
 if p_expected_revision is null then
  insert into public.review_tracker_connections(id,payload) values('google',p_payload)
  on conflict(id) do update set payload=excluded.payload,revision=gen_random_uuid(),updated_at=now() returning * into row_data;
 else
  update public.review_tracker_connections set payload=p_payload,revision=gen_random_uuid(),updated_at=now()
  where id='google' and revision=p_expected_revision returning * into row_data;
  if not found then return null; end if;
 end if;
 return jsonb_build_object('payload',row_data.payload,'revision',row_data.revision);
end;
$$;
create or replace function public.review_tracker_connection_delete() returns void
language plpgsql security invoker set search_path='' as $$
begin
 delete from public.review_tracker_connections where id='google';
 delete from public.review_tracker_kv where key like 'oauth:%';
end;
$$;

do $$
declare f record;
begin
  for f in select p.oid::regprocedure as signature from pg_proc p
    join pg_namespace n on p.pronamespace=n.oid
    where n.nspname='public' and p.proname in
      ('review_tracker_state','review_tracker_mutate','review_tracker_lock','review_tracker_unlock',
       'review_tracker_kv_get','review_tracker_kv_set','review_tracker_kv_delete','review_tracker_kv_take',
       'review_tracker_connection_get','review_tracker_connection_set','review_tracker_connection_delete')
  loop
    execute format('revoke execute on function %s from public, anon, authenticated',f.signature);
    execute format('grant execute on function %s to service_role',f.signature);
  end loop;
end;
$$;
notify pgrst, 'reload schema';
commit;
