import {useEffect,useState} from 'react';
import {api} from '../lib/api.js';
export default function SourceOverview({data,query}){
 const [summaries,setSummaries]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 async function load(){setBusy(true);setError('');try{setSummaries(await api('/api/ota/summary'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 const hotels=data.places.map(p=>({id:p.id,key:'google:'+p.id,name:p.name,google:[...data.rows].reverse().find(r=>r.values[p.id])?.values[p.id],sources:summaries.filter(s=>s.google_place_id===p.id)}));
 for(const s of summaries){if(s.google_place_id&&data.places.some(p=>p.id===s.google_place_id))continue;hotels.push({key:s.source+':'+s.property_id,name:s.property_name,sources:[s],unlinked:true});}
 const cell=s=>!s?<span className="source-missing">Chưa có dữ liệu</span>:<><strong>{s.rating==null?'—':Number(s.rating).toLocaleString('vi-VN')}/{s.ratingMax}</strong><div>{Number(s.count).toLocaleString('vi-VN')} đánh giá</div><small>{s.at?new Date(s.at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa rõ thời điểm'}{s.pilot?' · Đọc thử, chưa tự động':''}</small></>;
 return <section className="card source-overview"><div className="source-heading"><div><h2>Khách sạn theo từng nguồn</h2><p>Điểm và tổng đánh giá riêng của mỗi nền tảng. Giữ nguyên thang điểm gốc.</p></div><button onClick={load} disabled={busy}>{busy?'Đang tải OTA...':'Tải lại OTA'}</button></div>{error&&<p className="notice error" role="alert">Không tải được tổng hợp OTA: {error}</p>}<div className="source-scroll"><table><thead><tr><th>Khách sạn</th><th>Google Maps · /5 ⭐</th><th>Agoda · /10</th><th>Traveloka</th><th>Ctrip / Trip.com</th></tr></thead><tbody>{hotels.filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(p=><tr key={p.key}><th>{p.name}{p.unlinked&&<small>Chưa ghép với khách sạn Google</small>}</th><td>{cell(p.google?{rating:p.google.rating,ratingMax:5,count:p.google.reviews,at:p.google.capturedAt}:null)}</td>{['agoda','traveloka','trip'].map(source=>{const s=p.sources.find(s=>s.source===source);return <td key={source}>{cell(s?{rating:s.rating,ratingMax:s.rating_max,count:s.review_count,at:s.captured_at,pilot:s.is_pilot}:null)}</td>;})}</tr>)}</tbody></table></div>{!busy&&!hotels.length&&<p>Chưa có khách sạn hoặc nguồn dữ liệu đã kết nối.</p>}<p className="source-footnote">Các dòng OTA chưa ghép được giữ riêng để tránh gán nhầm khách sạn. Tổng review không cộng chung giữa các nguồn.</p></section>;
}
