import {useEffect,useState} from 'react';
import {api} from '../lib/api.js';
import Icon from './Icon.jsx';
export default function SourceOverview({data,query}){
 const [summaries,setSummaries]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(true),[search,setSearch]=useState('');
 async function load(){setBusy(true);setError('');try{setSummaries(await api('/api/ota/summary'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 const hotels=data.places.map(p=>({id:p.id,key:'google:'+p.id,name:p.name,google:[...data.rows].reverse().find(r=>r.values[p.id])?.values[p.id],sources:summaries.filter(s=>s.google_place_id===p.id)}));
 for(const s of summaries){if(s.google_place_id&&data.places.some(p=>p.id===s.google_place_id))continue;hotels.push({key:s.source+':'+s.property_id,name:s.property_name,sources:[s],unlinked:true});}
 const cell=s=>!s?<div className="source-missing"><span>—</span><small>Chưa có dữ liệu</small></div>:<div className="source-reading"><div className="source-rating"><Icon name="star" size={15}/><strong>{s.rating==null?'—':Number(s.rating).toLocaleString('vi-VN')}</strong><span>/{s.ratingMax}</span></div><div className="source-review-count">{Number(s.count).toLocaleString('vi-VN')} <span>đánh giá</span></div><small>{s.at?new Date(s.at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa rõ thời điểm'}</small>{s.pilot&&<span className="pilot-tag">Đọc thử · chưa tự động</span>}</div>;
 return <><div className="source-kpis">{[{label:"Khách sạn hiển thị",value:hotels.length,icon:"hotel",note:"Các bản ghi đã kết nối"},{label:"Nguồn có dữ liệu",value:new Set([...(hotels.some(p=>p.google)?["google"]:[]),...summaries.map(s=>s.source)]).size,icon:"link",note:"Google Maps và OTA"},{label:"Nguồn OTA thử nghiệm",value:summaries.filter(s=>s.is_pilot).length,icon:"shield",note:"Nguồn tổng hợp đang đọc thử"}].map(m=><div className="source-kpi" key={m.label}><span className="icon-box blue"><Icon name={m.icon}/></span><div><small>{m.label}</small><strong>{m.value}</strong><span>{m.note}</span></div></div>)}</div><section className="card source-overview"><div className="source-heading"><div><h2>Bảng theo dõi khách sạn</h2><p>Điểm và tổng đánh giá riêng của mỗi nền tảng. Giữ nguyên thang điểm gốc.</p></div><button onClick={load} disabled={busy}>{busy?'Đang tải OTA...':'Tải lại OTA'}</button></div>{error&&<p className="notice error" role="alert">Không tải được tổng hợp OTA: {error}</p>}<div className="source-toolbar"><label className="search-field"><Icon name="search"/><input aria-label="Tìm trong bảng nguồn" placeholder="Tìm khách sạn trong bảng..." value={search} onChange={e=>setSearch(e.target.value)}/></label><span>Điểm gốc theo từng nền tảng</span></div><div className="source-scroll"><table><thead><tr><th>Khách sạn</th><th><span className="platform google">G</span> Google Maps<small>Thang điểm 5 sao</small></th><th><span className="platform agoda">a</span> Agoda<small>Thang điểm 10</small></th><th><span className="platform traveloka">T</span> Traveloka<small>Điểm gốc nền tảng</small></th><th><span className="platform trip">C</span> Ctrip / Trip.com<small>Điểm gốc nền tảng</small></th></tr></thead><tbody>{hotels.filter(p=>p.name.toLocaleLowerCase().includes((search||query).toLocaleLowerCase())).map(p=><tr key={p.key}><th><span className="hotel-initial">{p.name.slice(0,2).toUpperCase()}</span>{p.name}{p.unlinked&&<small>Chưa ghép với khách sạn Google</small>}</th><td>{cell(p.google?{rating:p.google.rating,ratingMax:5,count:p.google.reviews,at:p.google.capturedAt}:null)}</td>{['agoda','traveloka','trip'].map(source=>{const s=p.sources.find(s=>s.source===source);return <td key={source}>{cell(s?{rating:s.rating,ratingMax:s.rating_max,count:s.review_count,at:s.captured_at,pilot:s.is_pilot}:null)}</td>;})}</tr>)}</tbody></table></div>{!busy&&!hotels.length&&<p>Chưa có khách sạn hoặc nguồn dữ liệu đã kết nối.</p>}<p className="source-footnote">Các dòng OTA chưa ghép được giữ riêng để tránh gán nhầm khách sạn. Tổng review không cộng chung giữa các nguồn.</p></section></>;
}
