import {useEffect,useState} from 'react';
import {api} from '../lib/api.js';
import {platforms,categories} from '../lib/directory.js';
import {alertText,time,visibleAlerts} from '../lib/insight-labels.js';
import Icon from '../components/Icon.jsx';
export default function Attention({onHistory,onEvidence}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[group,setGroup]=useState('managed'),[showRead,setShowRead]=useState(false),[category,setCategory]=useState('all');
 async function load(){setBusy(true);setError('');try{setData(await api('/api/insights?days=30'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function read(a){try{await api('/api/alerts/read',{method:'POST',body:JSON.stringify({key:a.key})});setData(d=>({...d,alerts:d.alerts.map(v=>v.key===a.key?{...v,read:true}:v)}));window.dispatchEvent(new Event('insights-updated'));}catch(e){setError(e.message);}}
 const alerts=visibleAlerts(data?.alerts).filter(a=>a.relationship===group&&(showRead||!a.read)&&(category==='all'||a.category===category)),affected=new Set(alerts.map(a=>a.entity_key));
 return <main className="content insights-page"><header className="page-header"><div><span className="eyebrow">THEO DÕI CHỦ ĐỘNG</span><h1>Cần chú ý hôm nay.</h1><p>Biến động điểm và tổng đánh giá trong 7 ngày gần nhất.</p></div><button className="secondary" disabled={busy} onClick={load}><Icon name="refresh"/>{busy?'Đang kiểm tra…':'Kiểm tra lại'}</button></header>{error&&<p role="alert" className="notice error">{error}</p>}
 <div className="insight-kpis"><section className="card"><small>Địa điểm cần chú ý</small><strong>{affected.size}</strong></section><section className="card"><small>Điểm / tổng giảm</small><strong>{alerts.filter(a=>a.type.endsWith('drop')).length}</strong></section><section className="card"><small>Điểm giảm</small><strong>{alerts.filter(a=>a.type==='rating_drop').length}</strong></section><section className="card"><small>Tổng đánh giá giảm</small><strong>{alerts.filter(a=>a.type==='count_drop').length}</strong></section></div>
 <section className="card insight-panel"><div className="insight-filters"><select aria-label="Nhóm cảnh báo" value={group} onChange={e=>setGroup(e.target.value)}><option value="managed">Công ty quản lý</option><option value="comparison">Đối thủ / so sánh</option></select><select aria-label="Loại địa điểm cảnh báo" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Tất cả loại địa điểm</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><label className="insight-checkbox"><input type="checkbox" checked={showRead} onChange={e=>setShowRead(e.target.checked)}/> Hiện cảnh báo đã xem</label></div>
 <div className="alert-list">{alerts.map(a=><article className={'alert-item '+a.severity} key={a.key}><span className={'severity-dot '+a.severity}/><div className="alert-item-body"><strong>{a.name} <span>{platforms[a.source]?.name}</span></strong><p>{alertText(a)}</p><small>{time(a.at)} · {categories[a.category]}{a.read?' · Đã xem':''}</small><div className="alert-item-actions"><button onClick={()=>onHistory({entity:a.entity_key,source:a.source})}>Xem lịch sử</button>{a.type.endsWith('drop')&&<button onClick={()=>onEvidence({entity:a.entity_key,source:a.source,historyId:a.id})}>Ảnh kiểm chứng</button>}{!a.read&&<button onClick={()=>read(a)}>Đánh dấu đã xem</button>}</div></div></article>)}</div>{!busy&&!alerts.length&&<div className="history-empty">Chưa có biến động cần chú ý.</div>}
 <p className="source-footnote">Cảnh báo điểm giảm từ 0,1 trên thang 5 hoặc 0,2 trên thang 10; tổng đánh giá chính xác giảm. Cảnh báo được kiểm tra mỗi phút khi phần mềm đang mở.</p></section>
 </main>;
}
