import {useEffect,useState} from 'react';
import {api,apiBlob} from '../lib/api.js';
import {platforms} from '../lib/directory.js';
import {number,time} from '../lib/insight-labels.js';
import Icon from '../components/Icon.jsx';
function EvidenceImage({event}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(!event?.has_image)return;let stopped=false,imageUrl;apiBlob('/api/evidence/'+event.id+'/image').then(blob=>{imageUrl=URL.createObjectURL(blob);if(stopped)URL.revokeObjectURL(imageUrl);else setUrl(imageUrl);}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;if(imageUrl)URL.revokeObjectURL(imageUrl);};},[event?.id,event?.has_image]);
 if(!event)return <div className="evidence-empty"><Icon name="review" size={30}/><p>Chưa có ảnh của mốc trước.</p></div>;
 if(!event.has_image)return <div className="evidence-empty"><Icon name="review" size={30}/><p>Mốc này chưa có ảnh được lưu.</p></div>;
 if(error)return <p className="notice error">{error}</p>;
 return url?<a href={url} target="_blank" rel="noopener noreferrer" aria-label="Mở ảnh kiểm chứng kích thước gốc"><img src={url} alt={'Ảnh nguồn tại '+time(event.rating_at||event.count_at)}/></a>:<div className="evidence-empty" role="status">Đang tải ảnh…</div>;
}
function Pane({title,event}){return <section className="card evidence-pane"><div className="source-heading"><div><small>{title}</small><h2>{event?time(event.rating_at||event.count_at):'Chưa có mốc'}</h2></div></div><div className="evidence-values"><span>Điểm <strong>{number(event?.rating)}{event?.rating!=null?' / '+event.rating_max:''}</strong></span><span>{event?.count_kind==='ratings'?'Lượt chấm điểm':'Tổng đánh giá'} <strong>{event?.count_display||number(event?.review_count)}</strong></span></div><EvidenceImage key={event?.id||'empty'} event={event}/></section>;}
export default function Evidence({focus={}}){
 const [directory,setDirectory]=useState([]),[entity,setEntity]=useState(focus.entity||''),[source,setSource]=useState(focus.source||'google'),[events,setEvents]=useState([]),[current,setCurrent]=useState(''),[previous,setPrevious]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let stopped=false;api('/api/directory').then(rows=>{if(!stopped){setDirectory(rows);setEntity(v=>rows.some(r=>r.entity_key===v)?v:rows.find(r=>r.relationship==='managed')?.entity_key||rows[0]?.entity_key||'');}}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;};},[]);
 useEffect(()=>{if(!entity)return;let stopped=false;setBusy(true);setError('');setEvents([]);setCurrent('');setPrevious('');api('/api/evidence?'+new URLSearchParams({entity,source})).then(rows=>{if(stopped)return;setEvents(rows);const chosen=rows.find(r=>String(r.id)===String(focus.historyId))||rows.find(r=>r.has_image)||rows[0];setCurrent(chosen?String(chosen.id):'');const at=rows.findIndex(r=>r.id===chosen?.id);setPrevious(String(rows.slice(at+1).find(r=>r.has_image)?.id||''));}).catch(e=>{if(!stopped)setError(e.message);}).finally(()=>{if(!stopped)setBusy(false);});return()=>{stopped=true;};},[entity,source,reload]);
 const selected=directory.find(e=>e.entity_key===entity),after=events.find(e=>String(e.id)===current),index=events.findIndex(e=>String(e.id)===current),beforeChoices=events.slice(index+1),before=beforeChoices.find(e=>String(e.id)===previous);
 function chooseEntity(value){setEntity(value);const sources=directory.find(r=>r.entity_key===value)?.sources||[];if(!sources.some(s=>s.source===source))setSource(sources[0]?.source||'google');}
 function chooseCurrent(value){setCurrent(value);const at=events.findIndex(e=>String(e.id)===value);setPrevious(String(events.slice(at+1).find(e=>e.has_image)?.id||''));}
 return <main className="content insights-page"><header className="page-header"><div><span className="eyebrow">KIỂM CHỨNG TỪ NGUỒN</span><h1>Ảnh trước & sau.</h1><p>Đối chiếu vùng số liệu của cùng một địa điểm, cùng nền tảng.</p></div></header>
 <section className="card history-filters"><label>Địa điểm<select aria-label="Địa điểm xem ảnh" value={entity} onChange={e=>chooseEntity(e.target.value)}>{directory.map(r=><option key={r.entity_key} value={r.entity_key}>{r.name}</option>)}</select></label><label>Nền tảng<select aria-label="Nền tảng xem ảnh" value={source} onChange={e=>setSource(e.target.value)}>{selected?.sources.map(s=><option key={s.source} value={s.source}>{platforms[s.source]?.name}</option>)}</select></label><button disabled={busy} onClick={()=>setReload(n=>n+1)}>Tải lại ảnh</button></section>
 {error&&<p className="notice error" role="alert">{error}</p>}<div className="evidence-selects"><label>Mốc trước<select aria-label="Mốc ảnh trước" value={before?.id||''} onChange={e=>setPrevious(e.target.value)}><option value="">Chưa chọn mốc trước</option>{beforeChoices.map(e=><option key={e.id} value={e.id}>{time(e.rating_at||e.count_at)}{e.has_image?' · Có ảnh':' · Chưa có ảnh'}</option>)}</select></label><label>Mốc sau<select aria-label="Mốc ảnh sau" value={current} onChange={e=>chooseCurrent(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{time(e.rating_at||e.count_at)}{e.has_image?' · Có ảnh':' · Chưa có ảnh'}</option>)}</select></label></div>
 <div className="evidence-grid"><Pane title="TRƯỚC" event={before}/><Pane title="SAU" event={after}/></div><p className="source-footnote">Ảnh thuộc đúng mốc đã xác minh, lưu trong bộ nhớ riêng và yêu cầu đăng nhập để xem. Một số mốc cũ hoặc nguồn API/email chưa có ảnh. Worker lưu ảnh đầu tiên mỗi ngày và ảnh khi số liệu thay đổi. Bấm ảnh để xem kích thước gốc.</p>
 </main>;
}
