import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend,ReferenceLine} from 'recharts';
import {api} from '../lib/api.js';
import {platforms} from '../lib/directory.js';
import {number,signed} from '../lib/insight-labels.js';
import {comparableGrowth} from '../lib/comparison.js';
export default function GrowthComparison(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[days,setDays]=useState(30),[left,setLeft]=useState(''),[right,setRight]=useState(''),[source,setSource]=useState('google');
 useEffect(()=>{let stop=false;setData(null);setError('');api('/api/insights?days='+days).then(d=>{if(!stop){setData(d);setLeft(v=>v||d.directory.find(e=>e.relationship==='managed')?.entity_key||'');setRight(v=>v||d.directory.find(e=>e.relationship==='comparison')?.entity_key||'');}}).catch(e=>{if(!stop)setError(e.message);});return()=>{stop=true;};},[days]);
 const own=(data?.directory||[]).filter(e=>e.relationship==='managed'),selected=own.find(e=>e.entity_key===left),competitors=(data?.directory||[]).filter(e=>e.relationship==='comparison'&&e.category===selected?.category),opponent=competitors.find(e=>e.entity_key===right)||competitors[0],commonSources=selected?.sources.filter(s=>!s.warning&&opponent?.sources.some(t=>t.source===s.source&&!t.warning))||[],chosen=commonSources.some(s=>s.source===source)?source:commonSources[0]?.source;
 const growth=data&&opponent&&chosen?comparableGrowth(data.daily,left,opponent.entity_key,chosen):{points:[],commonDays:0};
 return <main className="content insights-page"><header className="page-header"><div><span className="eyebrow">SO SÁNH CÙNG NỀN TẢNG</span><h1>So sánh tốc độ tăng.</h1><p>Theo dõi biến động tổng đánh giá của mình và địa điểm đối chiếu trong cùng thời gian.</p></div></header>{error&&<p className="notice error" role="alert">{error}</p>}
 <section className="card history-filters"><label>Địa điểm công ty<select aria-label="Địa điểm công ty để so sánh" value={left} onChange={e=>setLeft(e.target.value)}>{own.map(e=><option key={e.entity_key} value={e.entity_key}>{e.name}</option>)}</select></label><label>Địa điểm đối chiếu<select aria-label="Đối thủ để so sánh" value={opponent?.entity_key||''} onChange={e=>setRight(e.target.value)}>{competitors.map(e=><option key={e.entity_key} value={e.entity_key}>{e.name}</option>)}</select></label><label>Nền tảng<select aria-label="Nền tảng so sánh" value={chosen||''} onChange={e=>setSource(e.target.value)}>{commonSources.map(s=><option key={s.source} value={s.source}>{platforms[s.source]?.name}</option>)}</select></label><label>Khoảng ngày<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(d=><option key={d} value={d}>{d} ngày</option>)}</select></label></section>
 <div className="history-metrics">{[{name:selected?.name,value:growth.leftChange},{name:opponent?.name,value:growth.rightChange}].map((m,i)=><section className="card" key={i}><small>{m.name||'Chưa có địa điểm đối chiếu'}</small><strong>{signed(m.value)} {growth.kind==='ratings'?'lượt chấm điểm':'đánh giá'}</strong><span>{growth.start?growth.start+' → '+growth.end:'Cần 2 ngày chung có tổng chính xác'}</span></section>)}</div>
 <section className="card history-chart"><div className="source-heading"><div><h2>Tăng / giảm từ cùng một mốc gốc</h2><p>{chosen&&platforms[chosen].name} · {growth.commonDays} ngày có dữ liệu chung</p></div></div>{growth.points.length?<div className="history-chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={growth.points} margin={{top:20,right:25,left:15,bottom:10}}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="day" tickFormatter={d=>d.slice(8)+'/'+d.slice(5,7)}/><YAxis allowDecimals={false} tickFormatter={signed}/><ReferenceLine y={0} stroke="#a6b4c8"/><Tooltip formatter={(value,name,item)=>[signed(value)+' · Tổng: '+number(item.payload[item.dataKey==='left'?'left_total':'right_total']),name]}/><Legend/><Line name={selected.name} dataKey="left" stroke="#4169e1" strokeWidth={3} dot={{r:3}} connectNulls={false} isAnimationActive={false}/><Line name={opponent.name} dataKey="right" stroke="#21a57a" strokeWidth={3} dot={{r:3}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<div className="history-empty">{!data?'Đang tải dữ liệu…':!opponent?'Nhóm này chưa có địa điểm đối chiếu trong danh mục.':!chosen?'Hai địa điểm chưa có nền tảng chung.':'Chưa đủ hai ngày chung có tổng chính xác. Biểu đồ sẽ bổ sung khi có dữ liệu.'}</div>}<p className="source-footnote">Chỉ so sánh cùng nền tảng, cùng loại số đếm, cùng ngày đầu/cuối có dữ liệu chung. Không cộng tổng giữa các nguồn hoặc suy ra tăng trưởng qua ngày thiếu.</p></section>
 </main>;
}
