import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {api} from '../lib/api.js';
import {platforms,categories} from '../lib/directory.js';
import {dailyHistory,historyChange,localDay} from '../lib/history.js';
const number=value=>value==null?'—':Number(value).toLocaleString('vi-VN');
const time=value=>value?new Date(value).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'—';
const labels={success:'Thành công',partial:'Có dữ liệu một phần',failed:'Thất bại',baseline:'Mốc đã lưu'};
const errors={blocked:'Nguồn chặn truy cập',network:'Lỗi kết nối',missing_count:'Chưa đọc được tổng đánh giá',missing_rating:'Chưa đọc được điểm',approximate_count:'Chỉ có mốc tổng đánh giá',login_required:'Yêu cầu đăng nhập',app_required:'Yêu cầu mở ứng dụng',invalid_data:'Dữ liệu chưa xác minh',no_public_summary:'Chưa đọc được số liệu',browser_missing:'Thiếu trình duyệt',no_reviews:'Chưa có đánh giá'};
function ChartTooltip({active,payload,label,field}){
 const p=payload?.[0]?.payload;
 return active&&p?<div className="history-tooltip"><strong>{label}</strong><div>{field==='rating'?'Điểm':'Tổng'}: {number(p[field])}</div><small>Ghi nhận: {time(p[field==='rating'?'rating_at':'count_at'])}</small></div>:null;
}
export default function History(){
 const [directory,setDirectory]=useState([]),[entity,setEntity]=useState(''),[source,setSource]=useState('google'),[days,setDays]=useState(30),[history,setHistory]=useState({observations:[],runs:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[metric,setMetric]=useState('review_count');
 useEffect(()=>{let cancelled=false;api('/api/directory').then(rows=>{if(!cancelled){setDirectory(rows);setEntity(rows.find(r=>r.relationship==='managed')?.entity_key||rows[0]?.entity_key||'');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!entity)return;let cancelled=false;setBusy(true);setError('');setHistory({observations:[],runs:[]});api('/api/source-history?'+new URLSearchParams({entity,source,days})).then(data=>{if(!cancelled)setHistory(data);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[entity,source,days,reload]);
 const points=dailyHistory(history.observations),rating=historyChange(points,'rating'),count=historyChange(points,'review_count'),platform=platforms[source],kind=history.observations.some(r=>r.count_kind==='ratings')?'lượt chấm điểm':'đánh giá';
 const selected=directory.find(r=>r.entity_key===entity),sources=selected?.sources||[];
 function selectEntity(value){setEntity(value);const next=directory.find(r=>r.entity_key===value)?.sources||[];if(!next.some(s=>s.source===source))setSource(next[0]?.source||'google');}
 const change=value=>value==null?'Cần ít nhất 2 ngày có số liệu':(value>0?'+':'')+number(value)+' trong khoảng chọn';
 return <main className="page history-page"><div className="page-heading"><div><small>THEO DÕI BIẾN ĐỘNG</small><h1>Biểu đồ & lịch sử.</h1><p>Điểm và tổng đánh giá theo ngày, riêng cho từng địa điểm và nền tảng.</p></div></div>
 <section className="card history-filters"><label>Địa điểm<select aria-label="Địa điểm xem lịch sử" value={entity} onChange={e=>selectEntity(e.target.value)}>{directory.map(r=><option key={r.entity_key} value={r.entity_key}>{r.name} · {categories[r.category]}{r.relationship==='comparison'?' · So sánh':''}</option>)}</select></label><label>Nền tảng<select aria-label="Nền tảng xem lịch sử" value={source} onChange={e=>setSource(e.target.value)}>{sources.map(s=><option key={s.source} value={s.source}>{platforms[s.source]?.name||s.source}</option>)}</select></label><label>Khoảng ngày<select aria-label="Khoảng ngày" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90,365].map(d=><option key={d} value={d}>{d} ngày gần nhất</option>)}</select></label><button disabled={busy||!entity} onClick={()=>setReload(r=>r+1)}>{busy?'Đang tải…':'Tải lại lịch sử'}</button></section>
 {error&&<p className="notice error" role="alert">{error}</p>}
 <div className="history-metrics">{[{title:'Điểm gần nhất',value:number(rating.latest)+' / '+platform.scale,delta:rating.change},{title:'Tổng '+kind+' gần nhất',value:number(count.latest),delta:count.change}].map(m=><section className="card" key={m.title}><small>{m.title}</small><strong>{m.value}</strong><span className={m.delta>0?'history-up':m.delta<0?'history-down':''}>{change(m.delta)}</span></section>)}</div>
 <section className="card history-chart"><div className="source-heading"><div><h2>Xu hướng theo ngày</h2><p>{selected?.name} · {platform.name} · giờ Việt Nam</p></div><div className="history-tabs"><button aria-pressed={metric==='review_count'} onClick={()=>setMetric('review_count')}>Tổng {kind}</button><button aria-pressed={metric==='rating'} onClick={()=>setMetric('rating')}>Điểm / sao</button></div></div>
 {busy?<p role="status">Đang tải lịch sử…</p>:points.some(p=>p[metric]!=null)?<div className="history-chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:20,right:28,left:16,bottom:12}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" tickFormatter={d=>d.slice(8)+'/'+d.slice(5,7)} minTickGap={35}/><YAxis domain={metric==='rating'?[0,platform.scale]:[0,'auto']} allowDecimals={metric==='rating'} width={65}/><Tooltip content={<ChartTooltip field={metric}/>}/><Line type="linear" dataKey={metric} stroke={metric==='rating'?'#f59e0b':'#4169e1'} strokeWidth={3} dot={{r:4}} activeDot={{r:6}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<div className="history-empty">Chưa có mốc {metric==='rating'?'điểm':'tổng chính xác'} trong khoảng này. Các lần quét tiếp theo sẽ tự thêm dữ liệu.</div>}
 <p className="source-footnote">Mỗi ngày dùng lần đọc xác minh cuối cùng của từng chỉ số. Ngày thiếu số liệu để trống. Mốc như 10+ không dùng để tính tăng giảm; lịch sử trước khi bật tính năng chỉ gồm các mốc đã lưu.</p></section>
 <section className="card history-log"><div className="source-heading"><div><h2>Lịch sử từng lần làm mới</h2><p>200 mốc gần nhất trong khoảng chọn. Tải lại trang chỉ đọc dữ liệu đã lưu; worker thực hiện quét.</p></div></div><div className="source-scroll"><table><thead><tr><th>Ngày / giờ</th><th>Kết quả</th><th>Điểm</th><th>Tổng {kind}</th><th>Ghi chú</th></tr></thead><tbody>{history.runs.map((r,i)=><tr key={r.id}><td>{(i===0||localDay(r.attempted_at)!==localDay(history.runs[i-1].attempted_at))&&<strong className="history-day">{localDay(r.attempted_at)}</strong>}{time(r.attempted_at)}</td><td><span className={'history-status '+r.status}>{labels[r.status]}</span></td><td>{number(r.rating)}{r.rating!=null&&' / '+r.rating_max}<small>{r.rating_at&&time(r.rating_at)}</small></td><td>{r.count_display||number(r.review_count)}<small>{r.count_at&&time(r.count_at)}</small></td><td>{r.error?(errors[r.error]||r.error):r.status==='baseline'?'Số liệu đã lưu trước khi bật lịch sử':r.status==='partial'&&!r.rating_at&&!r.count_at?'Không có số liệu tổng mới':'Đã xác minh'}<small>{r.method==='ocr'?'Đọc ảnh':r.method==='dom'?'Đọc trang':r.method||''}</small></td></tr>)}</tbody></table></div>{!busy&&!history.runs.length&&<p className="history-empty">Chưa có lần làm mới trong khoảng chọn.</p>}</section>
 </main>;
}
