import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,BarChart,Bar,Cell,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine,LabelList} from 'recharts';
import {api} from '../lib/api.js';
import {platforms,categories} from '../lib/directory.js';
import {dailyHistory,historyChange,localDay,dailyChanges,ratingDomain} from '../lib/history.js';
import Icon from '../components/Icon.jsx';
const number=value=>value==null?'—':Number(value).toLocaleString('vi-VN');
const time=value=>value?new Date(value).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'—';
const labels={success:'Thành công',partial:'Đã làm mới',failed:'—',baseline:'Mốc đã lưu'};
const signed=value=>value==null?'—':(value>0?'+':'')+number(value);
const dayLabel=day=>day?day.slice(8)+'/'+day.slice(5,7)+'/'+day.slice(0,4):'';
const tickDay=day=>day.slice(8)+'/'+day.slice(5,7);
function ChartTooltip({active,payload,label,field,kind,scale}){
 const p=payload?.[0]?.payload;
 return active&&p?<div className="history-tooltip"><strong>{dayLabel(label)}</strong>{field==='count_change'?<><div className={p.count_change>0?'history-up':p.count_change<0?'history-down':''}>{signed(p.count_change)} {kind} so với ngày trước</div><div>{number(p.previous_count)} → {number(p.review_count)}</div><small>Mốc trước: {time(p.previous_count_at)}</small></>:<div>{field==='rating'?'Điểm':'Tổng '+kind}: {number(p[field])}{field==='rating'?' / '+scale:''}</div>}<small>Ghi nhận: {time(p[field==='rating'?'rating_at':'count_at'])}</small></div>:null;
}
function FirstObservation({value,at,unit,missing}){
 return <div className="history-first"><span className="history-first-icon"><Icon name="trend" size={24}/></span><strong>{number(value)} <span>{value!=null&&unit}</span></strong><p>{value==null?missing:'Mốc đầu tiên · '+dayLabel(localDay(at))}</p><small>{value==null?'Worker sẽ bổ sung khi đọc được số liệu.':'Biểu đồ sẽ xuất hiện khi có thêm một ngày có số liệu.'}</small></div>;
}
function CountBarLabel({value,viewBox,x,y,width}){
 const box=viewBox||{x,y,width};
 if(value==null||!Number.isFinite(box.x)||!Number.isFinite(box.y))return null;
 return <text x={box.x+box.width/2} y={value<0?box.y+15:box.y-8} textAnchor="middle" fill={value<0?'white':'#4e607a'} fontSize={12} fontWeight={700}>{signed(value)}</text>;
}
export default function History({focus={},onEvidence}){
 const [directory,setDirectory]=useState([]),[entity,setEntity]=useState(focus.entity||''),[source,setSource]=useState(focus.source||'google'),[days,setDays]=useState(30),[history,setHistory]=useState({observations:[],runs:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[countView,setCountView]=useState('change');
 useEffect(()=>{let cancelled=false;api('/api/directory').then(rows=>{if(!cancelled){setDirectory(rows);setEntity(v=>rows.some(r=>r.entity_key===v)?v:rows.find(r=>r.relationship==='managed')?.entity_key||rows[0]?.entity_key||'');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!entity)return;let cancelled=false;setBusy(true);setError('');setHistory({observations:[],runs:[]});api('/api/source-history?'+new URLSearchParams({entity,source,days})).then(data=>{if(!cancelled)setHistory(data);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[entity,source,days,reload]);
 const points=dailyHistory(history.observations),rating=historyChange(points,'rating'),count=historyChange(points,'review_count'),platform=platforms[source],kind=history.observations.some(r=>r.count_kind==='ratings')?'lượt chấm điểm':'đánh giá';
 const changes=dailyChanges(points),countPoints=points.filter(p=>p.review_count!=null),ratingPoints=points.filter(p=>p.rating!=null),bars=changes.filter(p=>p.count_change!=null),lastBar=bars.at(-1);
 const countLow=countPoints.length?Math.max(0,Math.min(...countPoints.map(p=>p.review_count))-Math.max(1,Math.ceil((Math.max(...countPoints.map(p=>p.review_count))-Math.min(...countPoints.map(p=>p.review_count)))*0.2))):0;
 const unchanged=bars.length>0&&bars.every(p=>p.count_change===0);
 const selected=directory.find(r=>r.entity_key===entity),sources=selected?.sources||[];
 function selectEntity(value){setEntity(value);const next=directory.find(r=>r.entity_key===value)?.sources||[];if(!next.some(s=>s.source===source))setSource(next[0]?.source||'google');}
 const change=value=>value==null?'Cần ít nhất 2 ngày có số liệu':(value>0?'+':'')+number(value)+' trong khoảng chọn';
 return <main className="page history-page"><div className="page-heading"><div><small>THEO DÕI BIẾN ĐỘNG</small><h1>Biểu đồ & lịch sử.</h1><p>Điểm và tổng đánh giá theo ngày, riêng cho từng địa điểm và nền tảng.</p></div></div>
 <section className="card history-filters"><label>Địa điểm<select aria-label="Địa điểm xem lịch sử" value={entity} onChange={e=>selectEntity(e.target.value)}>{directory.map(r=><option key={r.entity_key} value={r.entity_key}>{r.name} · {categories[r.category]}{r.relationship==='comparison'?' · So sánh':''}</option>)}</select></label><label>Nền tảng<select aria-label="Nền tảng xem lịch sử" value={source} onChange={e=>setSource(e.target.value)}>{sources.map(s=><option key={s.source} value={s.source}>{platforms[s.source]?.name||s.source}</option>)}</select></label><label>Khoảng ngày<select aria-label="Khoảng ngày" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90,365].map(d=><option key={d} value={d}>{d} ngày gần nhất</option>)}</select></label><button disabled={busy||!entity} onClick={()=>setReload(r=>r+1)}>{busy?'Đang tải…':'Tải lại lịch sử'}</button></section>
 {error&&<p className="notice error" role="alert">{error}</p>}
 <div className="history-metrics">{[{title:'Điểm gần nhất',value:number(rating.latest)+' / '+platform.scale,delta:rating.change},{title:'Tổng '+kind+' gần nhất',value:number(count.latest),delta:count.change}].map(m=><section className="card" key={m.title}><small>{m.title}</small><strong>{m.value}</strong><span className={m.delta>0?'history-up':m.delta<0?'history-down':''}>{change(m.delta)}</span></section>)}</div>
 <div className="history-context"><strong>{selected?.name}</strong><span>{platform.name} · giờ Việt Nam</span></div>
 <div className="history-chart-grid">
 <section className="card history-chart"><div className="source-heading"><div><small className="history-chart-eyebrow">SỐ LƯỢNG</small><h2>{countView==='change'?'Tăng / giảm mỗi ngày':'Tổng '+kind+' theo ngày'}</h2><p>{countView==='change'?'Chênh lệch tổng so với ngày liền trước.':'Số lượng chính xác tại mỗi mốc ghi nhận.'}</p></div><div className="history-tabs"><button aria-pressed={countView==='change'} onClick={()=>setCountView('change')}>Tăng / giảm</button><button aria-pressed={countView==='total'} onClick={()=>setCountView('total')}>Tổng tích lũy</button></div></div>
 {busy?<p className="history-empty" role="status">Đang tải lịch sử…</p>:countPoints.length<2?<FirstObservation value={count.latest} at={countPoints[0]?.count_at} unit={kind} missing="Chưa có tổng chính xác trong khoảng chọn."/>:countView==='change'&&!bars.length?<div className="history-empty history-gap"><Icon name="review" size={28}/><strong>Thiếu ngày liền trước để so sánh</strong><p>Các mốc tổng vẫn được lưu. Chọn “Tổng tích lũy” để xem.</p><button onClick={()=>setCountView('total')}>Xem tổng tích lũy</button></div>:<>
 {countView==='change'&&<div className="history-chart-summary"><strong className={lastBar?.count_change>0?'history-up':lastBar?.count_change<0?'history-down':''}>{signed(lastBar?.count_change)} <span>{kind}</span></strong><small>{lastBar&&dayLabel(lastBar.day)+' so với ngày trước'}</small></div>}
 <div className="history-chart-canvas"><ResponsiveContainer width="100%" height="100%">{countView==='change'?<BarChart data={changes} margin={{top:26,right:20,left:0,bottom:6}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf5"/><XAxis dataKey="day" tickFormatter={tickDay} minTickGap={35} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} width={50} domain={unchanged?[-1,1]:['auto','auto']} tickFormatter={signed} tickLine={false} axisLine={false}/><ReferenceLine y={0} stroke="#a6b4c8"/><Tooltip cursor={{fill:'#edf2fa'}} content={<ChartTooltip field="count_change" kind={kind}/>}/><Bar dataKey="count_change" maxBarSize={38} radius={4} isAnimationActive={false}>{changes.map(p=><Cell key={p.day} fill={p.count_change<0?'#e36b6b':p.count_change>0?'#21a57a':'#a2aec0'}/>)}{bars.length<=14&&<LabelList dataKey="count_change" content={<CountBarLabel/>}/>}</Bar></BarChart>:<AreaChart data={points} margin={{top:20,right:20,left:0,bottom:6}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf5"/><XAxis dataKey="day" tickFormatter={tickDay} minTickGap={35} tickLine={false} axisLine={false}/><YAxis domain={[countLow,'auto']} allowDecimals={false} width={60} tickLine={false} axisLine={false}/><Tooltip content={<ChartTooltip field="review_count" kind={kind}/>}/><Area dataKey="review_count" type="linear" stroke="#4169e1" fill="#4169e1" fillOpacity={0.1} strokeWidth={3} dot={{r:3,fill:'#4169e1'}} connectNulls={false} isAnimationActive={false}/></AreaChart>}</ResponsiveContainer></div>
 {countView==='change'?<div className="history-legend"><span><i className="up"/> Tăng</span><span><i className="down"/> Giảm</span><span><i className="flat"/> 0 = không thay đổi</span></div>:<p className="history-axis-note">Trục dọc thu hẹp để nhìn rõ biến động tổng.</p>}
 </>}
 <p className="source-footnote">{countView==='change'?'Chỉ so sánh hai ngày liền nhau có tổng chính xác. Số giảm phản ánh tổng nguồn giảm, không xác định nguyên nhân.':'Ngày thiếu tổng chính xác để trống; không nối qua ngày thiếu.'} Mốc 10+ / 50+ không dùng để tính chênh lệch.</p></section>
 <section className="card history-chart"><div className="source-heading"><div><small className="history-chart-eyebrow">ĐIỂM ĐÁNH GIÁ</small><h2>Điểm / sao theo ngày</h2><p>Thang điểm gốc {platform.name}: {platform.scale} điểm.</p></div><span className="history-scale">/{platform.scale}</span></div>
 {busy?<p className="history-empty" role="status">Đang tải lịch sử…</p>:ratingPoints.length<2?<FirstObservation value={rating.latest} at={ratingPoints[0]?.rating_at} unit={'/ '+platform.scale} missing="—"/>:<><div className="history-chart-summary"><strong>{number(rating.latest)} <span>/ {platform.scale}</span></strong><small className={rating.change>0?'history-up':rating.change<0?'history-down':''}>{rating.change===0?'Điểm không đổi trong khoảng chọn':signed(rating.change)+' điểm trong khoảng chọn'}</small></div><div className="history-chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:22,right:20,left:0,bottom:6}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf5"/><XAxis dataKey="day" tickFormatter={tickDay} minTickGap={35} tickLine={false} axisLine={false}/><YAxis domain={ratingDomain(points,platform.scale)} width={50} tickFormatter={number} tickLine={false} axisLine={false}/><Tooltip content={<ChartTooltip field="rating" scale={platform.scale}/>}/><Line dataKey="rating" type="linear" stroke="#e6a13b" strokeWidth={3} dot={{r:4,fill:'#e6a13b',stroke:'white',strokeWidth:2}} activeDot={{r:6}} connectNulls={false} isAnimationActive={false}>{ratingPoints.length<=14&&<LabelList dataKey="rating" position="top" formatter={value=>value==null?"":number(value)} style={{fill:'#98702f',fontSize:12,fontWeight:700}}/>}</Line></LineChart></ResponsiveContainer></div><p className="history-axis-note">Trục dọc thu hẹp để nhìn rõ thay đổi nhỏ của điểm.</p></>}
 <p className="source-footnote">Mỗi ngày dùng lần đọc điểm xác minh cuối cùng. Ngày chưa đọc được điểm để trống. Rê chuột để xem ngày, giá trị và giờ ghi nhận.</p></section>
 </div>
 <section className="card history-log"><div className="source-heading"><div><h2>Lịch sử từng lần làm mới</h2><p>200 mốc gần nhất trong khoảng chọn, gồm cập nhật tự động và nhập thủ công.</p></div></div><div className="source-scroll"><table><thead><tr><th>Ngày / giờ</th><th>Kết quả</th><th>Điểm</th><th>Tổng {kind}</th>{source==='tripadvisor'&&<th>Thứ hạng</th>}<th>Ghi chú</th><th>Ảnh</th></tr></thead><tbody>{history.runs.map((r,i)=><tr key={r.id}><td>{(i===0||localDay(r.attempted_at)!==localDay(history.runs[i-1].attempted_at))&&<strong className="history-day">{localDay(r.attempted_at)}</strong>}{time(r.attempted_at)}</td><td><span className={'history-status '+(r.status==='failed'?'':r.status)}>{labels[r.status]}</span></td><td>{number(r.rating)}{r.rating!=null&&' / '+r.rating_max}<small>{r.rating_at&&time(r.rating_at)}</small></td><td>{r.count_display||number(r.review_count)}<small>{r.count_at&&time(r.count_at)}</small></td>{source==='tripadvisor'&&<td>{r.rank_position!=null?<>#{Number(r.rank_position).toLocaleString('vi-VN')} trong {Number(r.rank_total).toLocaleString('vi-VN')} {({hotel:'khách sạn',restaurant:'nhà hàng',attraction:'điểm tham quan'})[r.rank_category]||'địa điểm'} tại {r.rank_area}<small>{r.rank_captured_at&&time(r.rank_captured_at)}</small></>:'—'}</td>}<td>{r.status==='baseline'?'Mốc đã lưu':r.rating_at||r.count_at?'Đã ghi nhận':'—'}<small>{r.method==='manual'?'Nhập thủ công':r.method==='ocr'?'Đọc ảnh':r.method==='dom'?'Đọc trang':r.method||''}</small>{r.note&&<small>{r.note}</small>}{r.entered_at&&<small>Nhập lúc: {time(r.entered_at)}</small>}</td><td>{r.status!=='failed'&&r.method!=='manual'&&<button className="evidence-link" onClick={()=>onEvidence?.({entity,source,historyId:r.id})}>Xem ảnh</button>}</td></tr>)}</tbody></table></div>{!busy&&!history.runs.length&&<p className="history-empty">Chưa có lần làm mới trong khoảng chọn.</p>}</section>
 </main>;
}
