import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api.js';
import {platforms,categories} from '../lib/directory.js';
import {number,signed,time,visibleReport} from '../lib/insight-labels.js';
import {excelReport,pdfReport} from '../lib/report-export.js';
import {reportView,reportGroups,reportSources,reportDate} from '../lib/report-view.js';
import Icon from '../components/Icon.jsx';
import {initialReportRange,reportToday,shiftReportDay} from '../lib/report-dates.js';
function Change({value,unit=''}){const tone=value==null||value===0?'neutral':value>0?'positive':'negative';return <span className={'report-change report-'+tone}>{value==null?'—':value===0?'Không đổi':signed(value)+(unit?' '+unit:'')}</span>;}
function Detail({group}){return <div className="report-detail"><h3>Mốc so sánh · {group.name}</h3><p>Cần ít nhất hai ngày có số liệu để tính tăng giảm.</p><div className="report-table-scroll"><table><thead><tr><th>Nền tảng</th><th>Đánh giá đầu → cuối</th><th>Thay đổi</th><th>Điểm đầu → cuối</th><th>Thay đổi điểm</th></tr></thead><tbody>{Object.values(group.sources).map(r=><tr key={r.source}><th>{platforms[r.source]?.name}<small>{r.count_kind==='ratings'?'Lượt chấm điểm':'Đánh giá'}</small></th><td>{number(r.review_count_first)} → {number(r.review_count)}<small>{reportDate(r.count_first_day)} → {reportDate(r.count_last_day)} · {r.count_days} ngày có tổng</small></td><td><Change value={r.count_change}/></td><td>{number(r.rating_first)} → {number(r.rating)} / {r.rating_max}<small>{reportDate(r.rating_first_day)} → {reportDate(r.rating_last_day)} · {r.rating_days} ngày có điểm</small></td><td><Change value={r.rating_change} unit="điểm"/></td></tr>)}</tbody></table></div></div>;}
export default function WeeklyReports(){
 const [data,setData]=useState(null),[archives,setArchives]=useState([]),[selected,setSelected]=useState('custom'),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(false);
 const [initial]=useState(initialReportRange),[from,setFrom]=useState(initial.start),[to,setTo]=useState(initial.end),[custom,setCustom]=useState(null);
 const [category,setCategory]=useState('all'),[source,setSource]=useState('all'),[query,setQuery]=useState(''),[movement,setMovement]=useState('all'),[metric,setMetric]=useState('count'),[expanded,setExpanded]=useState(null);
 const request=useRef(0),today=reportToday(),minimum=shiftReportDay(today,-364),valid=!!from&&!!to&&from<=to&&from>=minimum&&to<=today;
 async function load(mode=selected,start=from,end=to){
  const id=++request.current;setLoading(true);setError('');setExpanded(null);if(mode==='custom')setCustom(null);else setData(null);
  try{if(mode==='custom'){const result=await api('/api/reports?'+new URLSearchParams({start,end}));if(!result.report||result.report.version<3||result.report.start!==start||result.report.end!==end)throw new Error('Máy chủ chưa trả về mẫu báo cáo mới đúng khoảng ngày.');if(id===request.current)setCustom(result.report);}
   else{const result=await api('/api/reports');const saved=result.saved.find(r=>r.week_start===mode);if(saved&&saved.payload.version<3){if(saved.payload.start<minimum)throw new Error('Tuần lưu này nằm ngoài phạm vi 365 ngày của mẫu mới.');const fresh=await api('/api/reports?'+new URLSearchParams({start:saved.payload.start,end:saved.payload.end}));if(!fresh.report||fresh.report.version<3)throw new Error('Cần bản máy chủ báo cáo mới.');saved.payload={...fresh.report,recomputed:true};}if(id===request.current){setData(result);setArchives(result.saved);}}
  }catch(e){if(id===request.current)setError(e.message);}finally{if(id===request.current)setLoading(false);}
 }
 useEffect(()=>{let stopped=false;api('/api/reports').then(result=>{if(!stopped)setArchives(result.saved||[]);}).catch(()=>{});load('custom',initial.start,initial.end);return()=>{stopped=true;request.current++;};},[]);
 const candidate=selected==='custom'?(custom?.start===from&&custom?.end===to?custom:null):selected==='current'?data?.current:data?.saved.find(r=>r.week_start===selected)?.payload;
 const original=visibleReport(loading?null:candidate),report=reportView(original,{category,source,query,movement,metric}),groups=reportGroups(report?.rows||[]),sources=reportSources(report?.rows||[]);
 async function exportFile(type){setBusy(type);setError('');try{await(type==='excel'?excelReport(report):pdfReport(report));}catch(e){setError('Xuất báo cáo thất bại: '+e.message);}finally{setBusy('');}}
 function preset(days){const start=days==='week'?initial.start:days==='previous'?shiftReportDay(initial.start,-7):shiftReportDay(today,-days+1),end=days==='previous'?shiftReportDay(initial.start,-1):today;setSelected('custom');setFrom(start);setTo(end);load('custom',start,end);}
 return <main className="content insights-page report-page"><header className="page-header"><div><span className="eyebrow">HIỆU QUẢ THEO TỪNG ĐỊA ĐIỂM</span><h1>Báo cáo review.</h1><p>Điểm số, tổng đánh giá và biến động trong khoảng ngày bạn chọn.</p></div><div className="header-actions"><button className="secondary" disabled={!report||!report.rows.length||!!busy} onClick={()=>exportFile('excel')}><Icon name="download"/>{busy==='excel'?'Đang xuất…':'Xuất Excel'}</button><button className="primary" disabled={!report||!report.rows.length||!!busy} onClick={()=>exportFile('pdf')}><Icon name="download"/>{busy==='pdf'?'Đang xuất…':'Xuất PDF'}</button></div></header>{error&&<p className="notice error" role="alert">{error}</p>}
 <section className="card report-period"><div className="report-presets"><Icon name="calendar"/><strong>Khoảng báo cáo</strong>{[['week','Tuần này'],['previous','Tuần trước'],[7,'7 ngày'],[30,'30 ngày']].map(([value,label])=><button key={value} disabled={loading||!!busy} className="secondary" onClick={()=>preset(value)}>{label}</button>)}</div><div className="report-date-fields"><label>Mẫu báo cáo<select aria-label="Khoảng báo cáo" value={selected} disabled={loading||!!busy} onChange={e=>{setSelected(e.target.value);load(e.target.value);}}><option value="custom">Tự chọn ngày</option><option value="current">Tuần đang theo dõi</option>{archives.map(r=><option key={r.week_start} value={r.week_start} disabled={r.payload.version<3&&r.payload.start<minimum}>{reportDate(r.payload.start)} → {reportDate(r.payload.end)} · Tuần đã lưu</option>)}</select></label><label>Từ ngày<input aria-label="Báo cáo từ ngày" type="date" min={minimum} max={to||today} value={selected==='custom'?from:original?.start||''} disabled={selected!=='custom'||loading||!!busy} onChange={e=>{setFrom(e.target.value);setError('');}}/></label><label>Đến ngày<input aria-label="Báo cáo đến ngày" type="date" min={from||minimum} max={today} value={selected==='custom'?to:original?.end||''} disabled={selected!=='custom'||loading||!!busy} onChange={e=>{setTo(e.target.value);setError('');}}/></label><button className="primary" disabled={loading||!!busy||(selected==='custom'&&!valid)} onClick={()=>load()}><Icon name="refresh"/>{loading?'Đang tải…':'Xem báo cáo'}</button></div></section>
 {report?<><div className="report-summary-grid">{[{label:'Địa điểm đang xem',value:report.locations,icon:'hotel',tone:'blue'},{label:'Nguồn có điểm và tổng',value:report.confirmed_sources,icon:'check',tone:'blue'},{label:'Nguồn tăng tổng',value:report.rows.filter(r=>r.count_change>0).length,icon:'trend',tone:'green'},{label:'Nguồn giảm điểm',value:report.rows.filter(r=>r.rating_change!=null&&r.rating_change<0).length,icon:'star',tone:'orange'}].map(k=><section className={'card report-summary '+k.tone} key={k.label}><span className="report-summary-icon"><Icon name={k.icon}/></span><div><strong>{k.value}</strong><small>{k.label}</small></div></section>)}</div>
 <section className="card report-board history-log"><div className="report-board-head"><div><span className="eyebrow">{reportDate(report.start)} — {reportDate(report.end)}</span><h2>Bảng theo dõi địa điểm</h2><p>Mỗi địa điểm một dòng · Bấm tên để xem mốc đầu–cuối.</p></div><div className="report-metric-switch" role="group" aria-label="Chỉ số báo cáo"><button disabled={!!busy} aria-pressed={metric==='count'} onClick={()=>{setMetric('count');setMovement('all');}}>Số đánh giá</button><button disabled={!!busy} aria-pressed={metric==='rating'} onClick={()=>{setMetric('rating');setMovement('all');}}>Điểm số</button></div></div>
 <div className="report-controls"><label className="report-search"><Icon name="search"/><input aria-label="Tìm địa điểm trong báo cáo" placeholder="Tìm địa điểm…" value={query} disabled={!!busy} onChange={e=>{setQuery(e.target.value);setExpanded(null);}}/></label><select aria-label="Nhóm địa điểm báo cáo" value={category} disabled={!!busy} onChange={e=>{setCategory(e.target.value);setExpanded(null);}}><option value="all">Tất cả nhóm</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Nền tảng báo cáo" value={source} disabled={!!busy} onChange={e=>{setSource(e.target.value);setExpanded(null);}}><option value="all">Tất cả nền tảng</option>{reportSources(original.rows).map(k=><option key={k} value={k}>{platforms[k].name}</option>)}</select><select aria-label="Biến động báo cáo" value={movement} disabled={!!busy} onChange={e=>{setMovement(e.target.value);setExpanded(null);}}><option value="all">Tất cả biến động</option><option value="up">Đang tăng</option><option value="down">Đang giảm</option><option value="changed">Có thay đổi</option></select></div>
 {groups.length?<div className="report-table-scroll"><table className="report-matrix"><thead><tr><th>Địa điểm <small>{groups.length} địa điểm</small></th>{sources.map(s=><th key={s}>{platforms[s].name}<small>{metric==='rating'?'Điểm / '+platforms[s].scale:(report.rows.filter(r=>r.source===s&&r.review_count!=null).every(r=>r.count_kind==='ratings')&&report.rows.some(r=>r.source===s&&r.review_count!=null)?'Tổng lượt chấm':'Tổng đánh giá')}</small></th>)}</tr></thead><tbody>{groups.map(g=><tr key={g.key}><th><button className="report-place-button" aria-expanded={expanded===g.key} onClick={()=>setExpanded(expanded===g.key?null:g.key)}><span className="report-place-avatar">{g.name.split(' ').filter(Boolean).slice(0,2).map(w=>w[0]).join('')}</span><span>{g.name}<small>{categories[g.category]}</small></span><Icon name="chevron" size={15}/></button></th>{sources.map(s=>{const r=g.sources[s],value=metric==='rating'?r?.rating:r?.review_count,delta=metric==='rating'?r?.rating_change:r?.count_change;return <td key={s}>{r?<><strong className="report-main-value">{number(value)}{metric==='rating'&&value!=null&&<small>/{r.rating_max}</small>}</strong><Change value={delta} unit={metric==='rating'?'điểm':''}/><small className="report-secondary-value">{metric==='count'?(r.rating==null?'—':number(r.rating)+'/'+r.rating_max+' điểm'):(r.review_count==null?'—':number(r.review_count)+' '+(r.count_kind==='ratings'?'lượt chấm':'đánh giá'))}</small></>:<span className="report-unavailable">—</span>}</td>;})}</tr>)}</tbody></table></div>:<div className="history-empty">Không có địa điểm khớp bộ lọc.</div>}
 {expanded&&groups.some(g=>g.key===expanded)&&<Detail group={groups.find(g=>g.key===expanded)}/>}<div className="report-board-footer"><span><b>+</b> tăng · <b>−</b> giảm · <b>—</b> chưa đủ hai mốc</span><span>Excel / PDF xuất đúng bộ lọc đang xem.</span></div></section>
 <details className="report-method card"><summary>Cách đọc báo cáo và mốc dữ liệu</summary><p>{report.note}</p><p>Tạo lúc {time(report.generated_at)}. {original.recomputed?'Tuần cũ được tính lại từ lịch sử theo mẫu mới; bản lưu gốc vẫn được giữ.':selected==='custom'?'Tính cả ngày bắt đầu và kết thúc, theo giờ Việt Nam.':selected==='current'?'Tuần này cập nhật khi đọc báo cáo.':'Bản tuần đã kết thúc được giữ cố định.'}</p></details></>:<div className="card history-empty">{loading?'Đang tổng hợp số liệu…':error?'Báo cáo chưa tải được.':!valid?'Chọn khoảng ngày hợp lệ.':'Nhấn “Xem báo cáo” để theo dõi.'}</div>}
 </main>;
}
