import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api.js';
import {platforms} from '../lib/directory.js';
import {number,signed,time,visibleReport} from '../lib/insight-labels.js';
import {excelReport,pdfReport} from '../lib/report-export.js';
import Icon from '../components/Icon.jsx';
import {initialReportRange,reportToday,shiftReportDay} from '../lib/report-dates.js';
export default function WeeklyReports(){
 const [data,setData]=useState(null),[selected,setSelected]=useState('custom'),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(false);
 const [initial]=useState(initialReportRange),[from,setFrom]=useState(initial.start),[to,setTo]=useState(initial.end),[custom,setCustom]=useState(null);
 const request=useRef(0),today=reportToday(),minimum=shiftReportDay(today,-364);
 const valid=!!from&&!!to&&from<=to&&from>=minimum&&to<=today;
 async function load(mode=selected,start=from,end=to){
  const id=++request.current;setLoading(true);setError('');if(mode==='custom')setCustom(null);
  try{if(mode==='custom'){const result=await api('/api/reports?'+new URLSearchParams({start,end}));if(!result.report||result.report.start!==start||result.report.end!==end)throw new Error('Máy chủ chưa trả về báo cáo đúng khoảng ngày.');if(id===request.current)setCustom(result.report);}
   else{const result=await api('/api/reports');if(id===request.current)setData(result);}
  }catch(e){if(id===request.current)setError(e.message);}finally{if(id===request.current)setLoading(false);}
 }
 useEffect(()=>{let stopped=false;api('/api/reports').then(result=>{if(!stopped)setData(result);}).catch(()=>{});load('custom',initial.start,initial.end);return()=>{stopped=true;request.current++;};},[]);
 const candidate=selected==='custom'?(custom?.start===from&&custom?.end===to?custom:null):selected==='current'?data?.current:data?.saved.find(r=>r.week_start===selected)?.payload;
 const report=visibleReport(loading?null:candidate);
 function chooseMode(value){setSelected(value);load(value);}
 async function exportFile(type){setBusy(type);setError('');try{await(type==='excel'?excelReport(report):pdfReport(report));}catch(e){setError('Xuất báo cáo thất bại: '+e.message);}finally{setBusy('');}}
 return <main className="content insights-page"><header className="page-header"><div><span className="eyebrow">BÁO CÁO CHO QUẢN LÝ</span><h1>Báo cáo.</h1><p>Chọn khoảng ngày cần theo dõi hoặc xem báo cáo tuần đã lưu.</p></div><div className="header-actions"><button className="secondary" disabled={!report||!!busy} onClick={()=>exportFile('excel')}><Icon name="download"/>{busy==='excel'?'Đang xuất…':'Xuất Excel'}</button><button className="primary" disabled={!report||!!busy} onClick={()=>exportFile('pdf')}><Icon name="download"/>{busy==='pdf'?'Đang xuất…':'Xuất PDF'}</button></div></header>{error&&<p className="notice error" role="alert">{error}</p>}
 <section className="card history-filters report-range-filters"><label>Khoảng báo cáo<select aria-label="Khoảng báo cáo" value={selected} disabled={loading||!!busy} onChange={e=>chooseMode(e.target.value)}><option value="custom">Tự chọn ngày</option><option value="current">Tuần đang theo dõi</option>{data?.saved.map(r=><option key={r.week_start} value={r.week_start}>{r.payload.start} → {r.payload.end} · Tuần đã lưu</option>)}</select></label><label>Từ ngày<input aria-label="Báo cáo từ ngày" type="date" min={minimum} max={to||today} value={selected==='custom'?from:report?.start||''} disabled={selected!=='custom'||loading||!!busy} onChange={e=>{setFrom(e.target.value);setError('');}}/></label><label>Đến ngày<input aria-label="Báo cáo đến ngày" type="date" min={from||minimum} max={today} value={selected==='custom'?to:report?.end||''} disabled={selected!=='custom'||loading||!!busy} onChange={e=>{setTo(e.target.value);setError('');}}/></label><button disabled={loading||!!busy||(selected==='custom'&&!valid)} onClick={()=>load()}>{loading?'Đang tải…':'Xem báo cáo'}</button><small>Tính cả ngày bắt đầu và kết thúc, theo giờ Việt Nam. Có thể chọn trong 365 ngày gần nhất.</small></section>
 {report?<><div className="insight-kpis"><section className="card"><small>Địa điểm công ty</small><strong>{report.locations}</strong></section><section className="card"><small>Nguồn có điểm và tổng</small><strong>{report.confirmed_sources}</strong></section><section className="card"><small>Nguồn theo dõi</small><strong>{report.rows.length}</strong></section><section className="card"><small>Cảnh báo ghi nhận</small><strong>{report.alerts.length}</strong></section></div><p className="source-footnote">{report.start} → {report.end} · Tạo lúc {time(report.generated_at)}. {selected==='custom'?'Số liệu trong khoảng ngày bạn chọn.':selected==='current'?'Tuần này cập nhật khi đọc báo cáo.':'Bản tuần đã kết thúc được giữ cố định.'}</p>
 <div className="report-highlights"><section className="card insight-panel"><h2>Tăng tổng nổi bật</h2>{report.top_growth.length?report.top_growth.map(r=><div className="report-highlight" key={r.entity_key+':'+r.source}><span>{r.name}<small>{platforms[r.source]?.name} · {r.count_first_day} → {r.count_last_day}</small></span><strong className="history-up">{signed(r.count_change)}</strong></div>):<p className="history-empty">Chưa đủ dữ liệu để xếp hạng tăng trưởng.</p>}</section><section className="card insight-panel"><h2>Điểm cần theo dõi</h2>{report.rating_drops.length?report.rating_drops.map(r=><div className="report-highlight" key={r.entity_key+':'+r.source}><span>{r.name}<small>{platforms[r.source]?.name} · thang {r.rating_max}</small></span><strong className="history-down">{signed(r.rating_change)}</strong></div>):<p className="history-empty">Chưa ghi nhận điểm giảm đủ mốc trong khoảng chọn.</p>}</section></div>
 <section className="card history-log"><div className="source-heading"><div><h2>Số liệu theo địa điểm và nguồn</h2><p>{report.note}</p></div></div><div className="source-scroll"><table><thead><tr><th>Địa điểm</th><th>Nền tảng</th><th>Điểm</th><th>Thay đổi điểm</th><th>Tổng chính xác</th><th>Thay đổi tổng</th><th>Mốc tổng</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.entity_key+':'+r.source}><td>{r.name}</td><td>{platforms[r.source]?.name}</td><td>{number(r.rating)} / {r.rating_max}</td><td>{signed(r.rating_change)}</td><td>{number(r.review_count)}<small>{r.count_kind==='ratings'?'Lượt chấm điểm':'Đánh giá'}</small></td><td>{signed(r.count_change)}</td><td>{r.count_first_day||'—'} → {r.count_last_day||'—'}<small>{r.count_days} ngày có tổng · {r.rating_days} ngày có điểm</small></td></tr>)}</tbody></table></div></section></>:<p className="history-empty">{loading?'Đang tạo báo cáo từ số liệu đã lưu…':error?'Báo cáo chưa tải được.':!valid&&selected==='custom'?'Chọn ngày bắt đầu và kết thúc hợp lệ.':'Chọn khoảng ngày và nhấn “Xem báo cáo”.'}</p>}
 <p className="source-footnote">Báo cáo tự chọn ngày dùng số liệu đã lưu trong khoảng chọn. Báo cáo tuần đã chốt vẫn được giữ cố định.</p>
 </main>;
}
