import {useEffect,useState} from 'react';
import {api} from '../lib/api.js';
import {platforms} from '../lib/directory.js';
import {number,signed,time} from '../lib/insight-labels.js';
import {excelReport,pdfReport} from '../lib/report-export.js';
import Icon from '../components/Icon.jsx';
export default function WeeklyReports(){
 const [data,setData]=useState(null),[selected,setSelected]=useState('current'),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function load(){setError('');try{setData(await api('/api/reports'));}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 const report=selected==='current'?data?.current:data?.saved.find(r=>r.week_start===selected)?.payload;
 async function exportFile(type){setBusy(type);setError('');try{await(type==='excel'?excelReport(report):pdfReport(report));}catch(e){setError('Xuất báo cáo thất bại: '+e.message);}finally{setBusy('');}}
 return <main className="content insights-page"><header className="page-header"><div><span className="eyebrow">BÁO CÁO CHO QUẢN LÝ</span><h1>Báo cáo tuần.</h1><p>Tuần từ thứ Hai đến Chủ nhật, theo giờ Việt Nam.</p></div><div className="header-actions"><button className="secondary" disabled={!report||!!busy} onClick={()=>exportFile('excel')}><Icon name="download"/>{busy==='excel'?'Đang xuất…':'Xuất Excel'}</button><button className="primary" disabled={!report||!!busy} onClick={()=>exportFile('pdf')}><Icon name="download"/>{busy==='pdf'?'Đang xuất…':'Xuất PDF'}</button></div></header>{error&&<p className="notice error" role="alert">{error}</p>}
 <section className="card history-filters"><label>Tuần báo cáo<select aria-label="Tuần báo cáo" value={selected} onChange={e=>setSelected(e.target.value)}><option value="current">Tuần đang theo dõi</option>{data?.saved.map(r=><option key={r.week_start} value={r.week_start}>{r.payload.start} → {r.payload.end} · Đã lưu</option>)}</select></label><button onClick={load}>Tải lại báo cáo</button></section>
 {report?<><div className="insight-kpis"><section className="card"><small>Địa điểm công ty</small><strong>{report.locations}</strong></section><section className="card"><small>Nguồn có điểm và tổng</small><strong>{report.confirmed_sources}</strong></section><section className="card"><small>Nguồn thiếu dữ liệu</small><strong>{report.missing_sources}</strong></section><section className="card"><small>Cảnh báo ghi nhận</small><strong>{report.alerts.length}</strong></section></div><p className="source-footnote">{report.start} → {report.end} · Tạo lúc {time(report.generated_at)}. {selected==='current'?'Tuần này cập nhật khi đọc báo cáo.':'Bản tuần đã kết thúc được giữ cố định.'}</p>
 <div className="report-highlights"><section className="card insight-panel"><h2>Tăng tổng nổi bật</h2>{report.top_growth.length?report.top_growth.map(r=><div className="report-highlight" key={r.entity_key+':'+r.source}><span>{r.name}<small>{platforms[r.source]?.name} · {r.count_first_day} → {r.count_last_day}</small></span><strong className="history-up">{signed(r.count_change)}</strong></div>):<p className="history-empty">Chưa đủ dữ liệu để xếp hạng tăng trưởng.</p>}</section><section className="card insight-panel"><h2>Điểm cần theo dõi</h2>{report.rating_drops.length?report.rating_drops.map(r=><div className="report-highlight" key={r.entity_key+':'+r.source}><span>{r.name}<small>{platforms[r.source]?.name} · thang {r.rating_max}</small></span><strong className="history-down">{signed(r.rating_change)}</strong></div>):<p className="history-empty">Chưa ghi nhận điểm giảm đủ mốc trong tuần.</p>}</section></div>
 <section className="card history-log"><div className="source-heading"><div><h2>Số liệu theo địa điểm và nguồn</h2><p>{report.note}</p></div></div><div className="source-scroll"><table><thead><tr><th>Địa điểm</th><th>Nền tảng</th><th>Điểm</th><th>Thay đổi điểm</th><th>Tổng chính xác</th><th>Thay đổi tổng</th><th>Mốc tổng</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.entity_key+':'+r.source}><td>{r.name}</td><td>{platforms[r.source]?.name}</td><td>{number(r.rating)} / {r.rating_max}</td><td>{signed(r.rating_change)}</td><td>{number(r.review_count)}<small>{r.count_kind==='ratings'?'Lượt chấm điểm':'Đánh giá'}</small></td><td>{signed(r.count_change)}</td><td>{r.count_first_day||'—'} → {r.count_last_day||'—'}<small>{r.count_days} ngày có tổng · {r.rating_days} ngày có điểm</small></td></tr>)}</tbody></table></div></section></>:<p className="history-empty">{error?'Báo cáo chưa tải được.':'Đang tạo báo cáo từ số liệu đã lưu…'}</p>}
 <p className="source-footnote">Worker tự chốt tuần vừa kết thúc sau mỗi vòng quét. Phần mềm cũng kiểm tra chốt tuần khi mở mục này. Không gửi báo cáo hoặc thông báo ra email.</p>
 </main>;
}
