import test from 'node:test';
import assert from 'node:assert/strict';
import {parsePublicCard,aggregateFor} from '../src/public-summary.js';
test('reads actual Booking card instead of location subscore',()=>{assert.deepEqual(parsePublicCard('booking','9,5\nĐược điểm: Xuất sắc 9.5, dựa trên 175 đánh giá Mở rộng phần điểm đánh giá và đánh giá\nXuất sắc\n175 đánh giá'),{rating:9.5,reviewCount:175});assert.throws(()=>parsePublicCard('booking','Vị trí xuất sắc - được cho điểm 9.7/10!(điểm từ 174 đánh giá)'));});
test('uses Expedia review score, not hotel class',()=>{assert.deepEqual(parsePublicCard('expedia','Nhận xét\n9,8\n9,8 trên 10,\nNgoại hạng\nXem tất cả 155 nhận xét'),{rating:9.8,reviewCount:155});assert.throws(()=>parsePublicCard('expedia','Property class: 4'));});
test('reads TripAdvisor overall bubbles and exact total',()=>{assert.deepEqual(parsePublicCard('tripadvisor','4,9\n4,9 trên 5 bong bóng\n(77 đánh giá)'),{rating:4.9,reviewCount:77});});
test('Agoda branding label excludes the ten recent individual ratings',()=>{assert.deepEqual(parsePublicCard('agoda','Điểm số qua Agoda\n8,9/10\nTuyệt vời\nXu hướng xếp hạng gần đây\n9,6\n5,2\n10\nDựa trên 3.579 bài đánh giá'),{rating:8.9,reviewCount:3579});});
test('preserves ShopeeFood lower bound and ignores unrelated Foody score',()=>{assert.deepEqual(parsePublicCard('shopee','10+\nđánh giá trên ShopeeFood\nXem thêm lượt đánh giá từ Foody'),{rating:null,reviewCount:null,countDisplay:'10+'});assert.deepEqual(parsePublicCard('shopee','1\nđánh giá trên ShopeeFood'),{rating:null,reviewCount:1,countDisplay:null});});
test('rejects recommended merchants and reviewRating posing as aggregate',()=>{const url='https://food.grab.com/vn/en/restaurant/example/5-C7A1JXMWFGADDE';assert.equal(aggregateFor('grab',[JSON.stringify({'@id':'5-COTHER',aggregateRating:{ratingValue:5,ratingCount:100}})],url),null);assert.equal(aggregateFor('shopee',[JSON.stringify({url:'https://shopeefood.vn/now-food/shop/1',review:{reviewRating:{ratingValue:5}}})],'https://shopeefood.vn/now-food/shop/1'),null);});
